name: perubeca
description: aplicacion de peru beca del pronabec
version: 2.0.18+49
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.2.3
  connectivity_plus: ^6.1.3
  date_picker_plus: ^4.1.0
  device_info_plus: ^11.3.0
  #device_information: ^0.0.4
  dio: ^5.4.0
  dots_indicator: ^4.0.1
  dropdown_button2: ^2.1.3
  equatable: ^2.0.5
  fast_expressions: ^0.1.7
  firebase_analytics: ^11.4.3
  firebase_auth_web: ^5.9.4
  firebase_core: ^3.12.0
  firebase_crashlytics: ^4.3.3
  firebase_messaging: ^15.2.3
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_email_sender: ^7.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^19.0.0
  flutter_localizations:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_svg: ^2.0.5
  get_ip_address: ^0.0.5
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  images_cache: ^1.0.3
  intl: ^0.20.2
  nepali_date_picker: ^6.0.0
  network_info_plus: ^6.1.3
  open_file: ^3.5.10
  openid_client: ^0.4.7
  package_info_plus: ^8.2.1
  path_provider: ^2.0.15
  rxdart: ^0.28.0
  share_plus: ^10.1.4
  shared_preferences: ^2.3.3
  super_tooltip: ^2.0.2
  talker_dio_logger: ^4.0.0
  timer_count_down: ^2.2.2
  unique_identifier: ^0.4.0
  universal_html: ^2.2.3
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  webview_flutter: ^4.8.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  mocktail: ^1.0.3
  very_good_analysis: ^7.0.0

flutter:
  assets:
    - assets/
    - assets/login/
    - assets/static_data/
    - assets/static_data/prod/
    - assets/static_data/dev/
    - assets/static_data/stg/
    - assets/splash/
    - assets/info/
    - assets/menu/
    - assets/start/
    - assets/contact/
    - assets/enlace_relacionado/
    - assets/scholarship/
    - assets/scholarship/find/logos/
    - assets/scholarship/logos_bop/
    - assets/scholarship/detail/
    - assets/scholarship/zero/
    - assets/scholarship/view-sign/
    - assets/scholarship/syllabus/
    - assets/scholarship/formulario_imagenes/
    - assets/history/
    - assets/preparate_imagenes/alternativa/2/
    - assets/preparate_imagenes/alternativa/6/
    - assets/preparate_imagenes/alternativa/8/
    - assets/preparate_imagenes/alternativa/10/
    - assets/preparate_imagenes/alternativa/11/
    - assets/preparate_imagenes/alternativa/12/
    - assets/preparate_imagenes/alternativa/13/
    - assets/preparate_imagenes/areas/
    - assets/preparate_imagenes/menu/
    - assets/preparate_imagenes/pregunta/1/
    - assets/preparate_imagenes/pregunta/2/
    - assets/preparate_imagenes/pregunta/3/
    - assets/preparate_imagenes/pregunta/5/
    - assets/preparate_imagenes/pregunta/8/
    - assets/preparate_imagenes/pregunta/10/
    - assets/preparate_imagenes/pregunta/11/
    - assets/preparate_imagenes/pregunta/12/
    - assets/preparate_imagenes/pregunta/13/
    - assets/preparate_imagenes/solucionario/
    - assets/notice/

  fonts:
    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-Bold.ttf
          weight: 700
    - family: OpenSans-BoldItalic
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-BoldItalic.ttf
    - family: OpenSans-ExtraBold
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-ExtraBold.ttf
    - family: OpenSans-ExtraBoldItalic
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-ExtraBoldItalic.ttf
    - family: OpenSans-Light
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-Light.ttf
    - family: OpenSans-Medium
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-Medium.ttf
    - family: OpenSans-MediumItalic
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-MediumItalic.ttf
    - family: OpenSans-Regular
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-Regular.ttf
    - family: OpenSans-SemiBold
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-SemiBold.ttf
          weight: 500
    - family: OpenSans-SemiBoldItalic
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-SemiBoldItalic.ttf

    - family: Quicksand-Bold
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
          weight: 700
    - family: Quicksand-Light
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
    - family: Quicksand-Medium
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
    - family: Quicksand-Regular
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
    - family: Quicksand-SemiBold
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-SemiBold.ttf
          weight: 500

    - family: Roboto-Black
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
    - family: Roboto-BlackItalic
      fonts:
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
    - family: Roboto-BoldItalic
      fonts:
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
    - family: Roboto-Italic
      fonts:
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
    - family: Roboto-Light
      fonts:
        - asset: assets/fonts/roboto/Roboto-Light.ttf
    - family: Roboto-LightItalic
      fonts:
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
    - family: Roboto-MediumItalic
      fonts:
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
    - family: Roboto-Thin
      fonts:
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
    - family: Roboto-ThinItalic
      fonts:
        - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf  

  uses-material-design: true
  generate: true


