// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnkQovSa0i9ktb_Nh5bKwMfvgtdjuQ4Os',
    appId: '1:466919346846:web:92adb4e800cbddcb7ba18f',
    messagingSenderId: '466919346846',
    projectId: 'peru-beca-stg',
    authDomain: 'peru-beca-stg.firebaseapp.com',
    storageBucket: 'peru-beca-stg.appspot.com',
    measurementId: 'G-ZF4W9XCZYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLC6PjzYl9nho2V4NMMKV3GHAwArnogxU',
    appId: '1:466919346846:android:71b6666a70dc71417ba18f',
    messagingSenderId: '466919346846',
    projectId: 'peru-beca-stg',
    storageBucket: 'peru-beca-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhFwF5TM7I12ro4ySKMtNjVw-gQJWkTP0',
    appId: '1:466919346846:ios:9022f7fe33c848967ba18f',
    messagingSenderId: '466919346846',
    projectId: 'peru-beca-stg',
    storageBucket: 'peru-beca-stg.appspot.com',
    iosClientId: '466919346846-74e8ps83cludu7l5fqs6fng98ulvet8p.apps.googleusercontent.com',
    iosBundleId: 'com.perubeca.app.stg',
  );
}
