// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFcAV9AScfQciHC2yxAjBPgGpsplE_boo',
    appId: '1:324772752142:web:fe5208fff5110eb28c455f',
    messagingSenderId: '324772752142',
    projectId: 'peru-beca-dev',
    authDomain: 'peru-beca-dev.firebaseapp.com',
    storageBucket: 'peru-beca-dev.appspot.com',
    measurementId: 'G-V8KTBGMDG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF4vb-3BMkEt0cfEbodityetDXB9qMSTs',
    appId: '1:324772752142:android:de51ef9fa165aa328c455f',
    messagingSenderId: '324772752142',
    projectId: 'peru-beca-dev',
    storageBucket: 'peru-beca-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlkvTtf6649S5_BuDp1AfOuCVc21oqRz4',
    appId: '1:324772752142:ios:c664f3e503a847468c455f',
    messagingSenderId: '324772752142',
    projectId: 'peru-beca-dev',
    storageBucket: 'peru-beca-dev.appspot.com',
    iosClientId: '324772752142-t8s9uo3oovkk68v2vitagpi1gjme851j.apps.googleusercontent.com',
    iosBundleId: 'com.perubeca.app.dev',
  );
}
