// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdEZ6-bxfYNK_DxcrgE1CzeJz9Pr6QxX4',
    appId: '1:263095496960:web:719caba44a83b5e7df03e5',
    messagingSenderId: '263095496960',
    projectId: 'peru-beca-prod',
    authDomain: 'peru-beca-prod.firebaseapp.com',
    storageBucket: 'peru-beca-prod.appspot.com',
    measurementId: 'G-Z2EERN22JC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOpO5KdafSMjyd5wesSZqq3bvxs8yK360',
    appId: '1:263095496960:android:9870727b9413c8b8df03e5',
    messagingSenderId: '263095496960',
    projectId: 'peru-beca-prod',
    storageBucket: 'peru-beca-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRRB2Ivh53cDo9EThEgN1jJVuIZrojY6o',
    appId: '1:263095496960:ios:cdbdd38cec798facdf03e5',
    messagingSenderId: '263095496960',
    projectId: 'peru-beca-prod',
    storageBucket: 'peru-beca-prod.appspot.com',
    iosClientId: '263095496960-lois45kr7n65pu858d8ai0fiv9noco8r.apps.googleusercontent.com',
    iosBundleId: 'com.perubeca.app',
  );
}
