name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      - name: Clean Flutter and iOS build
        run: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Decode and save certificate
        env:
          CERTIFICATE_P12: ${{ secrets.CERTIFICATE_P12 }}
        run: |
          mkdir -p certs
          echo "${CERTIFICATE_P12}" | base64 --decode > certs/certificate.p12

      - name: Decode and save provisioning profile
        env:
          PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
        run: |
          mkdir -p certs
          echo "${PROVISIONING_PROFILE}" | base64 --decode > certs/profile.mobileprovision

      - name: Install provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ./certs/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Install certificate in keychain
        env:
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        run: |
          KEYCHAIN_PATH=$RUNNER_TEMP/build.keychain
          security create-keychain -p "" $KEYCHAIN_PATH
          security import ./certs/certificate.p12 -k $KEYCHAIN_PATH -P "${CERTIFICATE_PASSWORD}" -T /usr/bin/codesign
          security list-keychains -s $KEYCHAIN_PATH
          security default-keychain -s $KEYCHAIN_PATH
          security unlock-keychain -p "" $KEYCHAIN_PATH
          security set-keychain-settings -lut 3600 $KEYCHAIN_PATH

      - name: Build iOS app
        env:
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        run: |
          flutter build ipa --release -t lib/main_prod.dart --flavor production

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/ipa/*.ipa
